export const products = [
  {
    id: 'p1',
    name: '포근 도넛 베드',
    desc: '사계절 쓰는 분리형 커버 · S/M/L',
    category: '베드',
    price: 39900,
    image: '🛏️',
  },
  {
    id: 'p2',
    name: '영양 가득 닭가슴살 간식',
    desc: '저알러지 레시피 · 한 입 간식',
    category: '간식',
    price: 12900,
    image: '🍗',
  },
  {
    id: 'p3',
    name: '하루 한 줌 영양제',
    desc: '비타민·오메가3 · 피부/모질 케어',
    category: '영양제',
    price: 18900,
    image: '💊',
  },
  {
    id: 'p4',
    name: '초경량 산책 하네스',
    desc: '반려동물 체형 맞춤 · 통기성 우수',
    category: '산책용품',
    price: 25900,
    image: '🐕',
  },
  {
    id: 'p5',
    name: '흡수력 좋은 배변패드',
    desc: '대형 사이즈 · 냄새 차단',
    category: '배변·위생',
    price: 15900,
    image: '🧻',
  },
  {
    id: 'p6',
    name: '부드러운 웜 후드',
    desc: '겨울 방한 · 세탁 가능',
    category: '의류',
    price: 22900,
    image: '🧥',
  },
  {
    id: 'p7',
    name: '튼튼한 장난감 세트',
    desc: ' chew toy + 공 · 스트레스 해소',
    category: '장난감',
    price: 19900,
    image: '🎾',
  },
  {
    id: 'p8',
    name: '프리미엄 샴푸',
    desc: '저자극 거품 · 은은한 향',
    category: '목욕·미용',
    price: 14900,
    image: '🛁',
  },
];
